version: '3.3'
services:
  app:
    build: .
    ports:
    - '8080:8000'
#  mongo:
#    image: mongo:4.2.5
#  app:
#    build: .
#    environment:
#      WAIT_HOSTS: mongo:27017
#    ports:
#    -  '8080:8000'